server:
  port: 8082
#rocketmq:
#  consumer:
#    listeners: true
#  producer:
#    customized-trace-topic: s
#  name-server: ss
spring:
  #  kafka:
#    producer:
#      acks:
  rabbitmq:
    password: admin
    username: admin123
    host: 172.16.255.141
    port: 17725
    publisher-confirm-type: correlated
    publisher-confirms: true
    publisher-returns: true
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_order?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  cloud:
    stream:
      # Binder 配置项，对应 BinderProperties Map
      binders:
        rabbit001:
          type: rabbit # 设置 Binder 的类型
          environment: # 设置 Binder 的环境配置
            # 如果是 RabbitMQ 类型的时候，则对应的是 RabbitProperties 类
            spring:
              rabbitmq:
                host: 172.16.255.143
                port: 17725
                username: admin # RabbitMQ 服务的账号
                password: admin123 # RabbitMQ 服务的密码
                publisher-returns: true # 设置消息是否回退，默认为 false
                publisher-confirm-type: correlated # 设置开启消息确认模型，默认为 null 不进行确认
      rabbit:
        bindings:
          order-in-0:
            consumer:
              bindingRoutingKey: k.orderp.orderc.create
          order-out-0:
            producer:
              confirmAckChannel: acks
              exchangeType: direct
#              routing-key-expression: '''k.order.*.create'''
        binder:
          nodes: 172.16.255.141:17725
      bindings:
        order-in-0:
          destination: q.orderc
          group: orderp.create
#          consumer:
#            routing-key-expression: '''k.order'''
        order-out-0:
          destination: e.order #Exchange
          content-type: application/json # 内容格式。这里使用 JSON
#          binder: rabbit001 # 设置使用的 Binder 名字
          producer:
            error-channel-enabled: true # 是否开启异常 Channel，默认为 false 关闭
          group: order.group
#      default-binder: rabbit
  main:
    allow-bean-definition-overriding: true

cloud:
  stream:
    broker:
      address: 172.16.143.101:17725
      username: guest
      password: guest
      type: rabbit,kafka,rocketmq
    bindings:
      order-in-0:
        consumer:
          routing-key-expression: '''k.order'''
      order-out-0:
        producer:
          destination: e.order #Exchange
          group: order.group
          tx-message-type: local # local,rocketmq

seata:
  enabled: true
  application-id: order-service
  tx-service-group: my_test_tx_group
  #enable-auto-data-source-proxy: true
  #use-jdk-proxy: false
  client:
    rm:
      async-commit-buffer-limit: 1000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
    log:
      exceptionRate: 100
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    #enable-degrade: false
    #disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  config:
    type: file
    consul:
      server-addr: 127.0.0.1:8500
    apollo:
      apollo-meta: http://192.168.1.204:8801
      app-id: seata-server
      namespace: application
    etcd3:
      server-addr: http://localhost:2379
    nacos:
      namespace:
      serverAddr: localhost
      group: SEATA_GROUP
    zk:
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username: ""
      password: ""
  registry:
    type: file
    consul:
      cluster: default
      server-addr: 127.0.0.1:8500
    etcd3:
      cluster: default
      serverAddr: http://localhost:2379
    eureka:
      application: default
      weight: 1
      service-url: http://localhost:8761/eureka
    nacos:
      cluster: default
      server-addr: localhost
      namespace:
    redis:
      server-addr: localhost:6379
      db: 0
      password:
      cluster: default
      timeout: 0
    sofa:
      server-addr: 127.0.0.1:9603
      application: default
      region: DEFAULT_ZONE
      datacenter: DefaultDataCenter
      cluster: default
      group: SEATA_GROUP
      addressWaitTime: 3000
    zk:
      cluster: default
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username: ""
      password: ""
#management:

#  health.rabbitmq.enabled: false

