## 加解密根密码
#jasypt:
#  encryptor:
#    password: pig #根密码
#
## Spring 相关
#spring:
#  redis:
#    password:
#    host: pig-redis
#  main:
#    allow-bean-definition-overriding: true
#
## 暴露监控端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
## feign 配置
#feign:
#  hystrix:
#    enabled: true
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: false
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 10000
#  compression:
#    request:
#      enabled: true
#    response:
#      enabled: true
#
## hystrix 配置
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 60000
#  shareSecurityContext: true
#
##请求处理的超时时间
#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000
#
## mybaits-plus配置
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  global-config:
#    banner: false
#    db-config:
#      id-type: auto
#      table-underline: true
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  configuration:
#    map-underscore-to-camel-case: true
#
## spring security 配置
#security:
#  oauth2:
#    resource:
#      loadBalanced: true
#      token-info-uri: http://pig-auth/oauth/check_token
#
## swagger 配置
#swagger:
#  title: Pig Swagger API
#  license: Powered By pig4cloud
#  licenseUrl: https://pig4cloud.com
#  terms-of-service-url: https://pig4cloud.com
#  contact:
#    email: wangiegie@gmail.com
#    url: https://pig4cloud.com
#  authorization:
#    name: pig4cloud OAuth
#    auth-regex: ^.*$
#    authorization-scope-list:
#      - scope: server
#        description: server all
#    token-url-list:
#      - http://${GATEWAY-HOST:pig-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token