apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-kubernetes
  namespace: k8s
spec:
  selector:
    matchLabels:
      app: cloud-native-kubernetes
  template:
    metadata:
      labels:
        app: cloud-native-kubernetes
    spec:
      containers:
      - name: cloud-native-kubernetes
        image: cloud-native-kubernetes
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080