apiVersion: v1
kind: Service
metadata:
  name: cloud-native-kubernetes-service
  namespace: k8s
spec:
  type: NodePort
  selector:
    app: cloud-native-kubernetes
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30009
