spring:
  cloud:
    stream:
      function:
        definition: order
      bindings:
        order-out-0:
          destination: order-topic
          content-type: application/json
        order-in-0:
          destination: order-topic
          group: order-group
          consumer:
            concurrency: 2
            maxAttempts: 2
      kafka:
        binder:
          transaction:
            producer:
              batch-timeout:
        bindings:
      rabbit:
        bindings:
        binder:
          admin-addresses:
      rocketmq:
        binder:
          name-server: 172.16.143.101:9876
        bindings:
          order-out-0:
            producer:
              group: order-group
              transactional: true
          order-in-0:
            consumer:
              delayLevelWhenNextConsume: -1