spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jevon1994/spring-cloud-config
      label: master
  application:
    name: config-server
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
