spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mjevon/spring-cloud-config.git
      label: master
  application:
    name: config-server
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
